project:
  type: website
  output-dir: docs

website:
  title: "Utkarsh736"
  navbar:
    background: primary
    search: true
    left: 
      - text: "Home"
        href: index.qmd
      - blogs.qmd
    right:
      - icon: github
        href: https://github.com/Utkarsh736
      - icon: twitter
        href: https://twitter.com/Utkarsh736
format:
  html:
    theme: cosmo
    css: styles.css



